### ISSUE TITLE
Undefined Behavior in the siphash implementation

### ISSUE THREAD

**Issue by asquared31415** [rust-random/seeder#7]
The siphash implementation causes UB by reading multiple bytes from a pointer which can only read a single byte.
https://github.com/rust-random/seeder/blob/master/src/sip.rs#L110
I believe it would be wise to use a maintained crate for this implementation such as [`siphasher`](https://crates.io/crates/siphasher) (which does not have this bug as of version 0.3.9) as opposed to maintaining the current implementation which was copied from old rustc source.

**Comment by dhardy** [comment]
So this is https://github.com/jedisct1/rust-siphash/pull/16.

The relevant output from Miri:
```
test sip::test::test_hash_vectors ... error: Undefined Behavior: no item granting read access to tag <162148> at alloc61432+0x1 found in borrow stack.
    --> /home/dhardy/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2104:14
     |
2104 |     unsafe { copy_nonoverlapping(src, dst, count) }
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item granting read access to tag <162148> at alloc61432+0x1 found in borrow stack.
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
             
     = note: inside `core::intrinsics::copy_nonoverlapping::<u8>` at /home/dhardy/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2104:14
note: inside `sip::test::test_hash_vectors` at src/sip.rs:110:8
    --> src/sip.rs:110:8
     |
110  | /        ptr::copy_nonoverlapping($buf.get_unchecked($i),
111  | |                                 &mut data as *mut _ as *mut u8,
112  | |                                 mem::size_of::<$int_ty>());
     | |__________________________________________________________^
...
505  |           let (k0, k1) = unsafe{ (load_int_le!(&k_bytes, 0, u64), load_int_le!(&k_bytes, 8, u64)) };
     |                                   ------------------------------ in this macro invocation
```
So UB and a "potential bug" — from what I understand,

- [pointers carry "provenance" information in the Rust Abstract Machine](https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#pointer-provenance): at the very least, identifying the allocation a pointer comes from
- [slice::get_unchecked](https://doc.rust-lang.org/std/primitive.slice.html#method.get_unchecked) offsets the pointer then converts to a reference
- converting a pointer to a reference somehow "narrows provenance"; see [here for a discussion](https://users.rust-lang.org/t/pointer-provenance/38855)
- the point of all this is apparently to allow better analysis; e.g. to prove that mutable references to different slice elements do not alias with each other

So I'll fix this. As for using a maintained crate, if `siphasher` wants to add `SipRng` I'll be very happy to use that. Otherwise, I don't see a good reason to do anything different.
