### ISSUE TITLE
Publish a new release with a less-wide range of rand versions?

### ISSUE THREAD

**Issue by sunshowers** [rust-random/seeder#9]
Hi there --

We've been using rand_seeder for one of our projects at work, and it's been great, so thank you for maintaining it!

A problem we keep running into though is that we have both rand_core 0.5 and 0.6 in our dependency graph, but we want rand_seeder to only ever depend on 0.6. But often, `cargo update` (even if on completely unrelated dependencies) causes rand_seeder to "snap back" to rand_core 0.5.

This isn't really a rand_seeder issue -- it's a deficiency in Cargo. But I'm wondering if y'all would be open to publishing a new rand_seeder release (0.3.0 probably?) that only depends on rand_core 0.6.

Thanks!

**Comment by dhardy** [comment]
Hi,

I'm glad to hear that you've found use of it.

Yes, we can do that. We should:

- Bump the version to 0.3 and fix the `rand_core` version
- Update the changelog (check history since last release; probably very little)

If you make a PR then I will be happy to push a new release. Alternatively, wait until we release the next `rand_core` (hopefully not long now).

**Comment by sunshowers** [comment]
@dhardy thanks! Just put up #10 for this.
